<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="8" total="9" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-03-18T10:50:28 PDT" name="Default suite" finished-at="2022-03-18T10:50:42 PDT" duration-ms="13750">
    <groups>
      <group name="ContactPage">
        <method signature="ContactTests.messageField()[pri:0, instance:Tests.ContactTests@63021689]" name="messageField" class="Tests.ContactTests"/>
      </group> <!-- ContactPage -->
    </groups>
    <test started-at="2022-03-18T10:50:28 PDT" name="Default test" finished-at="2022-03-18T10:50:42 PDT" duration-ms="13750">
      <class name="Tests.ContactTests">
        <test-method is-config="true" signature="report(org.testng.ITestContext)[pri:0, instance:Tests.ContactTests@63021689]" started-at="2022-03-18T10:50:28 PDT" name="report" finished-at="2022-03-18T10:50:28 PDT" duration-ms="236" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@7ca8d498]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- report -->
        <test-method is-config="true" signature="initTest(org.testng.ITestContext)[pri:0, instance:Tests.ContactTests@63021689]" started-at="2022-03-18T10:50:28 PDT" name="initTest" finished-at="2022-03-18T10:50:35 PDT" duration-ms="7162" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@7ca8d498]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initTest -->
        <test-method signature="messageField()[pri:0, instance:Tests.ContactTests@63021689]" started-at="2022-03-18T10:50:35 PDT" name="messageField" finished-at="2022-03-18T10:50:42 PDT" duration-ms="6292" status="FAIL">
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 
at org.testng.AssertJUnit.fail(AssertJUnit.java:65)
at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:23)
at org.testng.AssertJUnit.assertFalse(AssertJUnit.java:44)
at org.testng.AssertJUnit.assertFalse(AssertJUnit.java:53)
at Tests.ContactTests.messageField(ContactTests.java:108)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- messageField -->
        <test-method is-config="true" signature="tearDownTest(org.testng.ITestContext)[pri:0, instance:Tests.ContactTests@63021689]" started-at="2022-03-18T10:50:42 PDT" name="tearDownTest" finished-at="2022-03-18T10:50:42 PDT" duration-ms="263" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@7ca8d498]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownTest -->
        <test-method is-config="true" signature="endReport(org.testng.ITestContext)[pri:0, instance:Tests.ContactTests@63021689]" started-at="2022-03-18T10:50:42 PDT" name="endReport" finished-at="2022-03-18T10:50:42 PDT" duration-ms="394" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@7ca8d498]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endReport -->
      </class> <!-- Tests.ContactTests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
